service: trpc-hello-world
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  http-api:
    name: 'ServerA'
    handler: .build/src/server-a/server.handler
    events:
      - httpApi: '*'
  rest-api:
    name: 'ServerB'
    handler: .build/src/server-b/server.handler
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-plugin-typescript
  - serverless-offline
